#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Reels Downloader (yt-dlp) - robustna verzia.
============================================
Opravuje situaciu: "ked je video obmedzene pre urcite publikum nejde stiahnut".

Co riesi oproti starej verzii:
  * age-restricted / 18+ / "not available in your country" / bot check
    -> pouziva prihlasene cookies + --age-limit + alternativny player client
  * nezastavi sa pri jednom chybnom linku -> pokracuje dalej
  * prehladny log + jasna chybova hlaska + napoveda pre bezne chyby
  * PO uspesnom stiahnuti sa link AUTOMATICKY odstrani z links.txt
  * spustenie:
        python reels_downloader.py                  # cita links.txt
        python reels_downloader.py -l "URL1" "URL2"
        python reels_downloader.py --browser chrome --out C:\\reels
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys

DEFAULT_OUT = os.path.join(os.path.expanduser("~"), "Downloads", "reels")
LINKS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "links.txt")

# Najbeznejsie prehliadace, z ktorych vieme zobrat prihlasene cookies.
BROWSERS = [
    "chrome", "chromium", "edge", "firefox", "opera", "brave",
    "vivaldi", "safari",
]


# --- Pomocne funkcie -----------------------------------------------------------

def tool(name):
    """Vrati True, ak je nastroj (yt-dlp/ffmpeg) dostupny v PATH."""
    return shutil.which(name) is not None


def check_tools():
    missing = [n for n in ("yt-dlp", "ffmpeg") if not tool(n)]
    if missing:
        print(f"[X] Chyba: {', '.join(missing)}")
        print("   Nainstaluj:  pip install -U yt-dlp   (ffmpeg daj do PATH)")
        return False
    return True


def normalize_link(line):
    line = (line or "").lstrip("\ufeff").strip()  # BOM (UTF-8 BOM) ignoruj
    if not line or not re.match(r"^https?://", line):
        return None
    return line


def read_links(args):
    links = []

    # 1) linky z argumentov
    for l in (args.links or []):
        n = normalize_link(l)
        if n and n not in links:
            links.append(n)

    # 2) linky zo suboru links.txt (v priecku tohto skriptu)
    if not links and os.path.isfile(LINKS_FILE):
        with open(LINKS_FILE, "r", encoding="utf-8") as f:
            for line in f:
                n = normalize_link(line)
                if n and n not in links:
                    links.append(n)

    return links


def drop_from_links(link):
    """Po uspesnom stiahnuti odstrani dany link z links.txt (ak tam je)."""
    if not os.path.isfile(LINKS_FILE):
        return False
    target = normalize_link(link)
    if target is None:
        return False
    with open(LINKS_FILE, "r", encoding="utf-8") as f:
        lines = f.readlines()
    kept = []
    removed = False
    for ln in lines:
        if normalize_link(ln) == target:
            removed = True
            continue
        kept.append(ln)
    if removed:
        with open(LINKS_FILE, "w", encoding="utf-8", newline="") as f:
            f.writelines(kept)
        print(f"   [~] Odstranene z links.txt: {link}")
    return removed


# --- Cookies: JSON (Cookie-Editor / EditThisCookie) -> Netscape format ----------

def json_cookies_to_netscape(json_path, out_path):
    """Prevedie cookies export v JSON (pole objektov) na Netscape cookies.txt."""
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    lines = ["# Netscape HTTP Cookie File", "# Generated by reels_downloader.py"]
    if isinstance(data, dict) and "cookies" in data:
        data = data["cookies"]  # niektoré exporty balia do {"cookies":[...]}
    for c in data:
        if not isinstance(c, dict):
            continue
        domain = c.get("domain", "")
        host_only = c.get("hostOnly", False)
        flag = "TRUE" if not host_only else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = 0
        if not c.get("session") and c.get("expirationDate"):
            try:
                exp = int(float(c["expirationDate"]))
            except (TypeError, ValueError):
                exp = 0
        name = c.get("name", "")
        value = c.get("value", "")
        if not domain or not name:
            continue
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{exp}\t{name}\t{value}")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return out_path


def ensure_netscape_cookies(cookies_path):
    """Ak je cookies subor v JSON (Cookie-Editor), prevedie ho na Netscape."""
    if not os.path.isfile(cookies_path):
        return cookies_path
    with open(cookies_path, "r", encoding="utf-8", errors="ignore") as f:
        head = f.read(256).lstrip()
    if head.startswith("["):
        base = os.path.splitext(cookies_path)[0]
        out = base + ".cookies.txt"
        try:
            json_cookies_to_netscape(cookies_path, out)
            print(f"   [~] Cookies JSON -> {os.path.basename(out)}")
            return out
        except Exception as e:
            print(f"   [i] Cookies JSON konverzia zlyhala ({e}) – pouzijem subor priamo.")
            return cookies_path
    return cookies_path


# --- Zostavenie prikazu pre yt-dlp ---------------------------------------------

# --- Zostavenie prikazu pre yt-dlp ---------------------------------------------

def build_cmd(link, cfg):
    cmd = ["yt-dlp"]

    # Vystupny vzor (povodny prieinok sa zachova: uploader_id)
    out = cfg.out or DEFAULT_OUT
    cmd += ["-o", os.path.join(out, "%(uploader)s_%(id)s.%(ext)s")]

    cmd += [
        "--no-playlist",   # stiahnut len to video, nie cely zoznam
        "--ignore-errors", # nema vymriet pri jednom chybnom linku
        "--newline",       # kazdy riadok logu na novy riadok (citelne)
        "--retries", "5",
        "--fragment-retries", "5",
        "--no-part",       # nechat finalny subor bez .part je cistejsie
    ]

    # -- Obmedzene / age-restricted videa -----------------------------------
    # povolit akykolvek vek: 18+ / "pre urcite publikum" uz nespadne ako chyba
    cmd += ["--age-limit", str(cfg.age_limit)]

    # prihlasene cookies = kluc k obmedzenemu obsahu (najcastejsia oprava)
    if cfg.cookies:
        cmd += ["--cookies", ensure_netscape_cookies(cfg.cookies)]
    elif cfg.browser:
        # yt-dlp vezme cookies priamo z prehliadaca
        cmd += ["--cookies-from-browser", cfg.browser]

    # alternativny player client pomaha obist "Sign in to confirm / not a bot"
    if cfg.player_client:
        cmd += ["--extractor-args", f"youtube:player_client={cfg.player_client}"]

    if cfg.proxy:
        cmd += ["--proxy", cfg.proxy]

    if cfg.extra:
        cmd += [a for a in cfg.extra.split() if a]

    # JS runtime (deno) zlepsuje extrakciu/deciphering na YouTube (age-gated formaty)
    # yt-dlp ho autodetekuje v PATH; ak je k dispozicii, explicitne ho zadame
    if shutil.which("deno") and "--js-runtimes" not in cmd:
        cmd += ["--js-runtimes", "deno"]


    cmd.append(link)
    return cmd


# --- Stiahnutie jedneho linku --------------------------------------------------

def download(link, cfg):
    cmd = build_cmd(link, cfg)
    print(f"\n[>] {link}")
    print("   " + " ".join(cmd))

    try:
        r = subprocess.run(cmd, capture_output=True, text=True)
    except Exception as e:
        print(f"   [X] Spustenie zlyhalo: {e}")
        return False

    if r.returncode == 0:
        print("   [OK]")
        return True

    # chybova hlaska (posledne riadky stderr)
    tail = [ln for ln in (r.stderr or "").splitlines() if ln.strip()]
    last = tail[-1] if tail else "nezname chyba"
    print(f"   [X] {last}")

    hint = hint_for_error(r.stderr or "")
    if hint:
        print(f"   [i] {hint}")
    return False



def hint_for_error(stderr):
    s = (stderr or "").lower()
    if "sign in" in s or ("age" in s and "restrict" in s) or "confirm your age" in s:
        return "Video je vekovo/targetovane obmedzene. Spusti s --browser chrome (alebo ten, kde si prihlaseny), aby sa pouzili tvoje cookies."
    if "not available in your" in s or "geo" in s or "region" in s:
        return "Video nie je dostupne pre tvoju krajinu - skus --proxy alebo inu IP."
    if "not a bot" in s or "bot" in s:
        return "YouTube Bot-check. Pouzi --browser chrome (prihlaseny) alebo --player-client."
    if "private" in s or "unavailable" in s or "removed" in s:
        return "Video je sukromne / odstrvene / nedostupne - neda sa stiahnut."
    if "login" in s or "oauth" in s or "cookies" in s:
        return "Potrebuje prihlasenie. Pouzi --cookies-from-browser <browser>."
    if "javascript runtime" in s or "js runtime" in s or "--js-runtimes" in s or "deprecated" in s:
        return "YouTube vyzaduje JS runtime. Nainstaluj deno (napr. npm i -g deno), potom skus znova − zlepsi extrakciu obmedzenych/age-gated formatov."

    return "Chyba moze byt docasna - skus to znova, pripadne aktualizuj yt-dlp:  yt-dlp -U"


# --- Main ----------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(
        description="Reels downloader cez yt-dlp (riesi obmedzene videa)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    p.add_argument("-l", "--links", nargs="*", default=[],
                   help="Zoznam URL. Ak vynasas, cita links.txt.")
    p.add_argument("--out", default=DEFAULT_OUT, help="Vystupny prieinok (default: ~/Downloads/reels)")
    p.add_argument("--browser", default=None, choices=BROWSERS,
                   help="Prehliadac s prihlasenim, odkial brat cookies")
    p.add_argument("--cookies", default=None,
                   help="cookies.txt (Netscape) alebo JSON export z Cookie-Editor/EditThisCookie (premeni sa automaticky)")
    p.add_argument("--age-limit", type=int, default=100,
                   help="Max. vek (default 100 = povolit 18+/obmedzene)")
    p.add_argument("--player-client", default="default,tv",
                   help="YouTube player client (napr. default,tv - pomaha s bot/age check)")
    p.add_argument("--proxy", default=None, help="Proxy URL")
    p.add_argument("--extra", default=None, help="Dalsie flagy pre yt-dlp (cely retazec)")
    cfg = p.parse_args()

    if not check_tools():
        return 1

    os.makedirs(cfg.out, exist_ok=True)

    links = read_links(cfg)
    if not links:
        print("[X] Ziadne linky. Vloz ich do links.txt alebo pouzi -l 'URL'.")
        return 1

    ok = fail = 0
    for link in links:
        if download(link, cfg):
            ok += 1
            drop_from_links(link)   # uspesne stiahnuty -> prec z links.txt
        else:
            fail += 1

    print(f"\n[F] Hotovo -> OK {ok}  X {fail}   |   prieinok: {cfg.out}")
    return 0 if fail == 0 else 2


if __name__ == "__main__":
    sys.exit(main())


